---
title: "Getting Pucks to the Net"
author: "Matt Kmiecik"
output:
  html_document:
    highlight: zenburn
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE, 
  message = FALSE,
  fig.align = "center",
  fig.path = "Pucks-to-the-Net"
  )
options(knitr.table.format = 'html') # For the html tables
```

These are the packages used for this analysis:

```{r, pkgs}
pkgs <- c("Hmisc", "tidyverse", "RColorBrewer", "RCurl", "broom")
xfun::pkg_attach(pkgs)
```

Retrieving the data:

```{r}
# Loading & prepping data ----
# data retrieved and downloaded from corsica.hockey on June 14 2019

# Link to retrive data from github repository
github_link <- "https://raw.githubusercontent.com/mkmiecik14/Blackhawk-Up/master/Data/nhl-team-stats-2007-2019.csv"

nhl_data <- read_csv(file = getURL(github_link)) %>% # retrieves data from github
  # edits name for WPG
  mutate(Team = ifelse(Team %in% c("ATL", "WPG"), "ATL.WPG", Team))

# Narrows down to essentials
shot_data <- nhl_data %>% 
  select(Team, Season, TOI, CF, GF) %>%
  mutate(CF_adj = CF/TOI, GF_adj = GF/TOI) # adjusting for TOI

# Models GF ~ CF
shot_data_mod <- shot_data %>%
  group_by(Season) %>%
  do(mod = lm(GF_adj ~ 1 + CF_adj, data = .))

shot_data_est <- shot_data_mod %>% tidy(mod) # retrieves estimates

ggplot(
  shot_data_est %>% filter(term %nin% "(Intercept)"),
  aes(Season, estimate)
  ) +
  geom_path(aes(group = 1), alpha = 1/3, linetype = 2) +
  geom_point() +
  geom_errorbar(
    aes(ymin = estimate - std.error, ymax = estimate + std.error),
    width = .1
    ) +
  theme_minimal()

ggplot(nhl_data, aes(CF, GF)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  facet_wrap(~Season) +
  theme_minimal()




```




